layout_spectrum: 0.4226409510928805
typography_spectrum: 0.1487650621259161
color:
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  brandStrength: 0.03631191068799189
  lightness: 0.42578240639677656
  saturation: 0.029451647925347386
  rhythmicContrast: 0.2009861322244316
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Uptime
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/34b60a6e-1e8f-4c31-8e77-d1412ccab06a.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/34b60a6e-1e8f-4c31-8e77-d1412ccab06a.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: UPTIME
description: You are always ahead of time !
author:
  name: Sandipan Banerjee
  email: ysiamhere@gmail.com
  url: 'https://ineventweb.wordpress.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/994dfb0d-7027-479c-8685-df9202573230.png
url: 'https://thegrid.ai/uptime/'
github: true
favicon: null
