layout_spectrum: 0.4226409510928805
typography_spectrum: 0.1487650621259161
color:
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  brandStrength: 0.03631191068799189
  lightness: 0.42578240639677656
  saturation: 0.029451647925347386
  rhythmicContrast: 0.2009861322244316
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Uptime
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FgIuuPTM3nSc%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DgIuuPTM3nSc&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FgIuuPTM3nSc%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Stephahahan
          url: 'https://www.youtube.com/user/stephahahan'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/ringo/img/favicon-vfl8qSV2F.ico'
        domain: www.youtube.com
      keywords:
        - the
        - real
        - adventures
        - of
        - jonny
        - quest
        - hanna
        - barbera
        - hq
        - hadji
        - benton
        - race
        - bannon
        - jessie
        - bandit
        - dr.
        - 3d
        - animation
        - graphics
        - tron
        - video
        - game
        - in...
      description: >-
        I can honestly say that this the best cartoon opening ever made. This
        cartoon aired in 1996-1997
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=gIuuPTM3nSc&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=gIuuPTM3nSc&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=gIuuPTM3nSc&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=gIuuPTM3nSc&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=gIuuPTM3nSc&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=gIuuPTM3nSc'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=gIuuPTM3nSc
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=gIuuPTM3nSc
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=gIuuPTM3nSc'
      title: The real adventures of Jonny Quest intro theme (best version)
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: Wiser Than Thou
description: 'Our storage your feed. OK? '
author:
  name: Sandipan Banerjee
  email: ysiamhere@gmail.com
  url: 'https://ineventweb.wordpress.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/994dfb0d-7027-479c-8685-df9202573230.png
url: 'https://thegrid.ai/uptime/'
github: true
favicon: null
