layout_spectrum: 0.9195677153659192
typography_spectrum: 0.3418318177334559
color:
  brandColors:
    - '#E7E8D1'
    - '#D3CEAA'
    - '#FBF7E4'
    - '#424242'
    - '#8E001C'
  brandStrength: 0.8703930502778638
  lightness: 0.8194220416694142
  saturation: 0.8390295088219244
  rhythmicContrast: 0.0781336050142193
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Uptime
content: []
title: UPTIME
description: You are always ahead of time !
author:
  name: Sandipan Banerjee
  email: ysiamhere@gmail.com
  url: 'https://ineventweb.wordpress.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/994dfb0d-7027-479c-8685-df9202573230.png
url: 'https://thegrid.ai/uptime/'
github: true
favicon: null
